export const GET_RATES = 'GET_RATES';

export const SET_FROM_CURRENCY = 'SET_FROM_CURRENCY';
export const SET_TO_CURRENCY = 'SET_TO_CURRENCY';

export const UPDATE_TRAINS_DETAILS = 'UPDATE_TRAINS_DETAILS';
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_GET_TRAINS_INFO_ERROR = 'SET_GET_TRAINS_INFO_ERROR';
export const SET_GET_TRAIN_DETAILS_ERROR = 'SET_GET_TRAIN_DETAILS_ERROR';
